name: blizzard_intl
description: "Simple internationalization and localization of Flutter apps"
version: 0.1.0
homepage: https://github.com/joshua-obritsch/blizzard_intl

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
